### ISSUE TITLE
Unclear Exception Message

### ISSUE THREAD

**Issue by jdrew82** [networktocode/diffsync#61]
### Environment
* DiffSync version:  1.3.0
* Python version  3.7

### Observed Behavior
When attempting a diff between two SoTs using the SSoT plugin I get the following Exception error:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/diffsync/__init__.py", line 543, in diff_from
    return differ.calculate_diffs()
  File "/usr/local/lib/python3.7/site-packages/diffsync/helpers.py", line 92, in calculate_diffs
    self.diff.add(diff_element)
  File "/usr/local/lib/python3.7/site-packages/diffsync/diff.py", line 58, in add
    raise ObjectAlreadyExists(f"Already storing a {element.type} named {element.name}")
diffsync.exceptions.ObjectAlreadyExists: Already storing a port named 0/0
```

This error message is unhelpful as I can't determine from the error message what's the parent context the Object is in relation to.

### Expected Behavior
I would expect more information to be provided in the error message denoting the parent context of the Object that already exists so further investigation of the issue can be done. The current message is unhelpful as I have no idea which device the 0/0 port is on that it's referencing.

### Steps to Reproduce
1. Create an application that utilizes DiffSync.
2. Have duplicate items in diff to cause Exception.
3. Attempt diff and expect Exception to be thrown.

**Comment by dgarros** [comment]
Please can you provide your DiffSyncModel for `port`

**Comment by dgarros** [comment]
@jdrew82 as a workaround, if you remove the line `_shortname = ("name",)` from your model it will report the full name of the object that is generating the exception.

Not 100% sure if this something that should be fixed or if this is the expected behavior ...

**Comment by jdrew82** [comment]
> @jdrew82 as a workaround, if you remove the line `_shortname = ("name",)` from your model it will report the full name of the object that is generating the exception.
> 
> Not 100% sure if this something that should be fixed or if this is the expected behavior ...

I was able to address this by not having the model be a top-level. I only created this issue as @glennmatthews requested that I do so to improve the logging information returned. If possible it'd be great if you could provide the parent context the object is in relation to. The error message as I provided isn't helpful as I have no idea which interface it's talking about.
